name: code-reviewer

services:
  postgres:
    container_name: code_reviewer_postgres
    image: postgres:15.4
    environment:
      - POSTGRES_PASSWORD=farisej11
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  mongo:
    container_name: code_reviewer_mongo
    image: mongo:6.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-changeme}
    volumes:
      - mongo_data:/data/db
      - ./config/mongodb/mongod.conf:/etc/mongod.conf
    ports:
      - "27017:27017"
    command: ["mongod", "--config", "/etc/mongod.conf"]

  redis:
    container_name: code_reviewer_redis
    image: redis:7.2.1
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  postgres_data:
    name: code_reviewer_postgres_data
  mongo_data:
  redis_data:

networks:
  code_reviewer_network:
    driver: bridge